-- ak je rezervácia na nejaké parkovacie miesto, iné si to nemôže rezervova
CREATE OR REPLACE TRIGGER REZERVACIA_OBSADENA
BEFORE INSERT ON REZERVACIA_PARK_MIESTA
FOR EACH ROW
DECLARE POCET INTEGER;
BEGIN
    SELECT COUNT(*) INTO POCET
      FROM REZERVACIA_PARK_MIESTA RPM
INNER JOIN  REZERVACIA REZ
        ON RPM.ID_REZERVACIA = REZ.ID_REZERVACIA
     WHERE RPM.ID_MIESTA = :NEW.ID_MIESTA
       AND EXISTS(SELECT 'X' 
              FROM REZERVACIA_PARK_MIESTA RPMNEW 
        INNER JOIN REZERVACIA REZNEW
                ON RPMNEW.ID_REZERVACIA = REZNEW.ID_REZERVACIA
             WHERE RPMNEW.ID_MIESTA != RPM.ID_MIESTA
               AND RPMNEW.ID_REZERVACIA NOT IN RPM.ID_REZERVACIA
               AND (REZNEW.ZACIATOK >= REZ.ZACIATOK
               AND REZNEW.ZACIATOK <= (REZ.ZACIATOK + REZ.DLZKA))
                OR ((REZNEW.ZACIATOK + REZNEW.DLZKA) >= REZ.ZACIATOK
               AND (REZNEW.ZACIATOK + REZNEW.DLZKA) <= (REZ.ZACIATOK + REZ.DLZKA))
        );
    IF(POCET != 0)
        THEN RAISE_APPLICATION_ERROR(-20001, 'Rezervácia na danom mieste sa prekrýva s už existujúcou rezerváciou.'); 
    END IF;
END;
/

SHOW ERROR;

INSERT INTO REZERVACIA_PARK_MIESTA 
    VALUES (21,21,517);
    
INSERT INTO REZERVACIA
    VALUES (21,226,NULL,'09.06.2017','SCH','+02 00:00:00.000000');
    